import pyautogui as p
from selenium import webdriver

chrome_options = webdriver.ChromeOptions()
chrome_options.add_argument("--incognito")

driver = webdriver.Chrome(chrome_options=chrome_options)
driver.maximize_window()
driver.get('https://github.com/')

p.sleep(3)
p.click(1298,150)
p.sleep(3)
p.typewrite('thiagoaugusto.franca@hotmail.com')
p.hotkey('tab')
p.typewrite('senhasecreta')
p.sleep(3)
p.hotkey('enter')
p.sleep(7)
p.click(1528,136)
p.sleep(5)
p.click(1461,307)
p.sleep(7)
p.click(1363,268)
p.sleep(7)
p.hotkey('tab')
p.typewrite('rep_Atividade_PyAutoGui')
p.sleep(3)
p.hotkey('tab')
p.sleep(3)
p.typewrite('Descricao teste')
p.sleep(3)
p.hotkey('tab')
p.sleep(3)
p.hotkey('tab')
p.sleep(3)
p.hotkey('space')
p.sleep(5)
p.scroll(-500)
p.sleep(5)
p.click(497,686)
p.sleep(10)

# Copiando https do rep
p.click(1026,316)
p.sleep(3)
p.click(724,451)
p.sleep(3)
p.click(1038,496)
p.sleep(5)

# Clonando e criando arquivo
p.click(168,882)
p.sleep(3)
p.typewrite('cd doc')
p.sleep(2)
p.hotkey('tab')
p.sleep(2)
p.hotkey('enter')
p.sleep(2)
p.typewrite('git clone ')
p.hotkey('ctrl', 'v')
p.sleep(2)
p.hotkey('enter')
p.sleep(5)
p.typewrite('cd rep')
p.hotkey('tab')
p.sleep(2)
p.hotkey('enter')
p.sleep(2)
p.typewrite('code .')
p.sleep(3)
p.hotkey('enter')
p.sleep(10)
btn_max = p.locateCenterOnScreen('max_window.png')
p.click(btn_max)
p.moveTo(174,187)
p.sleep(3)
btn_create = p.locateCenterOnScreen('createnewfile.png')
p.click(btn_create)
p.sleep(3)
p.typewrite('atividade.py')
p.sleep(3)
p.hotkey('enter')
p.sleep(3)
p.typewrite('print("Hello World")')
p.sleep(3)
btn_play = p.locateCenterOnScreen('btn_play.png')
p.click(btn_play)